# Generated by Django 3.1.6 on 2022-01-14 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailautomate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timeOfSendingMail',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 11, 35, 9, 653705)),
        ),
    ]
